# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('data_version', models.IntegerField()),
                ('state', models.IntegerField()),
                ('status', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('data_version', models.IntegerField()),
                ('state', models.IntegerField()),
                ('status', models.IntegerField()),
                ('order_no', models.CharField(max_length=255)),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('lable', models.IntegerField()),
                ('contacts', models.CharField(max_length=20)),
                ('contacts_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('pics_id', models.BigIntegerField(blank=True, null=True)),
                ('city_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InformationPic',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pic_url', models.CharField(max_length=255)),
                ('information_id', models.BigIntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('data_version', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('openid', models.CharField(max_length=255)),
                ('union_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
